name: Code Review

permissions:
  contents: read
  pull-requests: write

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - name: ChatGPT Code Review
        uses: anc95/ChatGPT-CodeReview@main
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          GITHUB_TOKEN:   ${{ secrets.GITHUB_TOKEN }}

          LANGUAGE:        Korean
          MODEL:           gpt-4.1-nano
          OPENAI_API_ENDPOINT: https://api.openai.com/v1

          PROMPT: |
            You are an AI code review assistant.
            Follow these conventions strictly:
            - Private methods must catch all exceptions using try–catch.
            - Public methods must NOT use any try–catch.

            Produce exactly these sections:

            1. Changed Files
            2. Key Changes
            3. Exception Handling Violations
               (only if violations exist)
               
          top_p:        1
          temperature:  1
          max_tokens:   10000

          MAX_PATCH_LENGTH: 10000
          IGNORE_PATTERNS: /node_modules/**/*,*.md
          INCLUDE_PATTERNS: *.java