name: ChatGPT Code Review Supporter

permissions:
  contents: read
  pull-requests: write

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  code-review:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: ChatGPT Code Review
        uses: anc95/ChatGPT-CodeReview@main
        with:
          openai_api_key: ${{ secrets.OPENAI_API_KEY }}
          github_token:   ${{ secrets.GITHUB_TOKEN }}
          model:          gpt-4.1-nano
          language:       Korean
          prompt: |
            You are an AI code review assistant.
            Follow these conventions strictly:
            - Private methods must catch all exceptions using try窶田atch.
            - Public methods must NOT use any try窶田atch.

            Produce exactly these sections:

            1. Changed Files
               - List each changed file path.

            2. Key Changes
               - Bullet-point main modifications.

            3. Exception Handling Violations
               (Only include this section if any violations exist.)
               - Private methods throwing without try窶田atch: File, Method, Exception.
               - Public methods using try窶田atch: File, Method, Caught exception.